# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('level', models.PositiveSmallIntegerField()),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('code', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('catchcopy', models.TextField()),
                ('caption', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('review_count', models.PositiveIntegerField()),
                ('review_average', models.PositiveSmallIntegerField()),
                ('url', models.CharField(max_length=2048)),
                ('image_url', models.CharField(max_length=2048)),
                ('shop_code', models.CharField(max_length=64)),
                ('shop_url', models.CharField(max_length=2048)),
                ('genres', models.ManyToManyField(to='rakuten.Genre')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'get_latest_by': 'modified',
                'ordering': ('-modified', '-created'),
                'abstract': False,
            },
        ),
    ]
